name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: cachix/install-nix-action@v2
    - name: Cachix
      uses: cachix/cachix-action@v2
      with:
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - name: Set up Cachix
      run: cachix use marvin
    - name: Build
      run: nix-shell ./shell.nix --run "cargo build"
    - name: Run tests
      run: nix-shell ./shell.nix --run "cargo test"
    - name: Clippy
      run: nix-shell ./shell.nix --run "cargo clippy"
    - name: Rustfmt
      run: nix-shell ./shell.nix --run "cargo fmt -- --check"
    - name: Update Cachix
      run: nix-store -qR $(nix-instantiate ./shell.nix) | cachix push marvin
